18.3.0442-ver3.4.1-CRF981

diff --git a/etc/init.d/nqe b/etc/init.d/nqe
--- a/etc/init.d/nqe
+++ b/etc/init.d/nqe
@@ -12,6 +12,71 @@ USE_PROCD=1
 
 . $IPKG_INSTROOT/lib/functions/contentsharing.sh
 
+add_samba_firewall_rules() {
+
+    local enable_wan=$(uci get samba.userauth.wan_access)
+      
+    if [ $enable_wan != 0 ] ; then
+       
+      procd_open_data
+
+      json_add_array firewall
+
+        json_add_object ""
+        json_add_string type rule
+        json_add_string src "lan"
+        json_add_string family any
+        json_add_string proto tcp
+        json_add_string dest_port "445"
+        json_add_string target accept
+        json_close_object
+
+        json_add_object ""
+        json_add_string type rule
+        json_add_string src "wan"
+        json_add_string family any
+        json_add_string proto tcp
+        json_add_string target accept
+        json_add_string dest_port "445" 
+        json_close_object
+
+      json_close_array
+
+      procd_close_data
+     
+
+    elif [ $enable_wan == 0 ] ; then
+
+      procd_open_data
+
+      json_add_array firewall
+
+        json_add_object ""
+        json_add_string type rule
+        json_add_string src "wan"
+        json_add_string family any
+        json_add_string proto tcp
+        json_add_string dest_port "445"
+        json_add_string target reject
+        json_close_object
+     
+      json_close_array
+
+      procd_close_data
+
+    fi
+}
+
+service_started() {
+  
+  procd_set_config_changed firewall
+}
+
+stop_service() {
+  
+  procd_set_config_changed firewall
+}
+
 start_service() {
         ln -sf /etc/init.d/nqe /etc/init.d/samba
 
@@ -32,6 +97,7 @@ start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/nqnd
        procd_set_param respawn
+       add_samba_firewall_rules
        procd_close_instance
 
 
@@ -83,7 +149,7 @@ local sambashare_printer_enabled=$(uci get $sambashare_printer_path)
 
 local printershare=$(transformer-cli get uci.printersharing. | grep name)
 
-if [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 0 ]] ; then
+if [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 0 && -n "$printershare" ]] ; then
   echo "$printershare" | while read line
   do
     local share_name_path=$(echo "$line" | cut -d' ' -f1)
@@ -95,7 +161,7 @@ if [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 0 ]] ; then
       /usr/bin/nqcsctrl -S $share_name
     fi
   done
-elif [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 1 ]] ; then
+elif [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 1 && -n "$printershare" ]] ; then
   echo "$printershare" | while read line
   do
     local share_name_path=$(echo "$line" | cut -d' ' -f1)
@@ -105,9 +171,29 @@ elif [[ $sambashare_printer_enabled == 1 && $printersharing_enabled == 1 ]] ; th
 
     local share_present=$(/usr/bin/nqcsctrl ES | grep -c $share_name)
 
-    if [ $share_present == 0 ] ; then
+    if [[ $share_present == 0 && -n "$share_path" ]] ; then
       /usr/bin/nqcsctrl +S $share_name $share_path $share_name
     fi
   done
 fi
+
+#signal message 
+procd_send_signal samba 
+
+if [ $? -eq 0 ]; then
+    # We need to call the start function once again in order to overwrite
+    # firewall rules.
+    # Because the process is already there, procd will not actually restart
+    start
+else
+    echo "Reload of samba failed. nqcs/nqnd not yet running?"
+fi
+# make sure the last statement of the reload function is always true
+# otherwise init.d will restart samba/nqe on failure of the reload function
+# and that can lead to an unwanted racecondition during boot time
+true
+
+
+
 }
+
